server:
  port: 8083

spring:
  application:
    name: sales-service
  data:
    mongodb:
      database: sales
      port: 27018
      host: vendas-mongo

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
    nonSecurePort: 8083


cart:
  url: "http://carrinho-mongo-app-instance:8082/v1/api/cart/%s"